In [1]:
import numpy as np

output_dir = './demo/output/custom2d/'

keypoints = np.load(output_dir + 'output_3D/' + f'output_keypoints_3d_regression.1.bias.npz', allow_pickle=True)['reconstruction']
keypoints

array([[[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [-1.11362055e-01,  9.07092355e-03,  3.79220285e-02],
         [-2.20280796e-01,  8.96124095e-02, -3.17598641e-01],
         ...,
         [-1.45347506e-01, -2.90458798e-01, -1.53516494e-02],
         [-2.03640446e-01, -8.14355016e-02,  3.29059884e-02],
         [-1.97489679e-01,  7.34783709e-03, -1.90827698e-01]],

        [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [-1.11159205e-01,  9.04470403e-03,  3.81344110e-02],
         [-2.19420224e-01,  9.12353471e-02, -3.17556977e-01],
         ...,
         [-1.45069987e-01, -2.93030083e-01, -1.17675178e-02],
         [-2.03333542e-01, -8.48106295e-02,  3.87120992e-02],
         [-1.98896244e-01,  5.21115959e-03, -1.85645580e-01]],

        [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [-1.12632871e-01,  8.64558853e-03,  3.85969616e-02],
         [-2.15535820e-01,  9.75739062e-02, -3.15389335e-01],
         ...,
         [-1.49116009e-0

In [2]:
keypoints.shape
# (person, frames, keypoint, coordinate)
# Kicker: 0, Goalkeeper: 1

(2, 20, 17, 3)

In [3]:
keypoints[0]

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.11362055e-01,  9.07092355e-03,  3.79220285e-02],
        [-2.20280796e-01,  8.96124095e-02, -3.17598641e-01],
        ...,
        [-1.45347506e-01, -2.90458798e-01, -1.53516494e-02],
        [-2.03640446e-01, -8.14355016e-02,  3.29059884e-02],
        [-1.97489679e-01,  7.34783709e-03, -1.90827698e-01]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.11159205e-01,  9.04470403e-03,  3.81344110e-02],
        [-2.19420224e-01,  9.12353471e-02, -3.17556977e-01],
        ...,
        [-1.45069987e-01, -2.93030083e-01, -1.17675178e-02],
        [-2.03333542e-01, -8.48106295e-02,  3.87120992e-02],
        [-1.98896244e-01,  5.21115959e-03, -1.85645580e-01]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.12632871e-01,  8.64558853e-03,  3.85969616e-02],
        [-2.15535820e-01,  9.75739062e-02, -3.15389335e-01],
        ...,
        [-1.49116009e-01, -2.96980590e-01,

In [4]:
keypoints[1]

array([[[ 0.        ,  0.        ,  0.        ],
        [-0.1266976 ,  0.00572198,  0.00077164],
        [-0.12293618,  0.26553723, -0.1772846 ],
        ...,
        [-0.13293487, -0.42082065, -0.01403726],
        [-0.14795828, -0.16475755, -0.08422881],
        [-0.08320582,  0.03933346, -0.19040218]],

       [[ 0.        ,  0.        ,  0.        ],
        [-0.1263654 ,  0.00580456,  0.00074713],
        [-0.12216196,  0.26330775, -0.17872241],
        ...,
        [-0.13258012, -0.42111748, -0.01493815],
        [-0.14803918, -0.16507548, -0.0848898 ],
        [-0.08357733,  0.03726967, -0.19386767]],

       [[ 0.        ,  0.        ,  0.        ],
        [-0.12661298,  0.00560665,  0.00072979],
        [-0.1225874 ,  0.26387724, -0.1777412 ],
        ...,
        [-0.1322394 , -0.42068195, -0.01446014],
        [-0.14724524, -0.16445473, -0.08473431],
        [-0.08307888,  0.03681834, -0.19370675]],

       ...,

       [[ 0.        ,  0.        ,  0.        ],
        [-0